jwt:
  header: Authorization
  # echo spring-boot-init-security-jwt-token-secret-key-hs512-64bytes-need | base64
  secret: c3ByaW5nLWJvb3QtaW5pdC1zZWN1cml0eS1qd3QtdG9rZW4tc2VjcmV0LWtleS1oczUxMi02NGJ5dGVzLW5lZWQK
  token-validity-in-seconds: 86400

spring:
  profiles:
    active: local
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${url:jdbc:mariadb://localhost:3306/spring-init}
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: never
      platform: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-init
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect